### ISSUE TITLE
Running on macOS

### ISSUE THREAD

**Issue by niksy** [NitriKx/docker-Plex-Cleaner#4]
Running `docker run -ti -v ~/Projects/plex-cleaner-test/config:/config -e "EXECUTION_CRON_EXPRESSION=ONCE" nitrikx/plex-cleaner --test` on macOS High Sierra gives me the following output:

```sh
Executing the script once...
/app/run-plexcleaner.sh --test

====================================================
Mon May  7 12:30:30 UTC 2018 - Running script
Loading config file: /config/Cleaner.conf
Traceback (most recent call last):
  File "/app/PlexCleaner.py", line 1054, in <module>
    options = json.loads(opt_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Am I doing something wrong?

**Comment by niksy** [comment]
Related to https://github.com/ngovil21/Plex-Cleaner/pull/61, but since that’s fixed there, why isn’t that fixed here?

**Comment by NitriKx** [comment]
Travis has not been triggered by the pull request merging. I'm relaunching it.
